[package]
name = "aeroshell"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
reedline = "0.45.0"
toml = "0.9.11"
nu-ansi-term = "0.50.3"
